s3:
        bucket: staging-server-files
        s3_region: ap-south-1
        access_key_id: AWIAQDSOUIMMJKHZQYR6
        secret_access_key: baqM43+Is6cxvGkc0jBPF1CutwWhHX6Ce8zbtbJD
        cloudfront_url: 